[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.cibuildwheel.linux]
before-all = "yum install unixODBC-devel"

[[tool.cibuildwheel.overrides]]
select = "*-musllinux*"
before-all = "apk add unixodbc-dev gcc g++"
